category_id: "1187112364898799746"
priority_category_id: "1217200478694277222"
authorized_roles: 
  - "1166995041642876938"
priority_role: "1216187687191580692"
priority_emoji: "üö®"
categories:
- name: "Supporto Generale"
  description: "Informazioni, Segnalazioni, Bug e Contestazioni"
  id: "supporto_generale"
  emoji: "üì©"
  questions:
    - title: "Domanda 1"
      question: "Quale domanda 1 ci sar√† qui?"
    - title: "Domanda 2"
      question: "Quale domanda 2 ci sar√† qui?"
    - title: "Domanda 3"
      question: "Quale domanda 3 ci sar√† qui?"

- name: "Account"
  description: "Problematiche relative al tuo account"
  id: "account"
  emoji: "üî©"
  questions:
    - title: "Domanda 1"
      question: "Quale domanda 1 ci sar√† qui?"
    - title: "Domanda 2"
      question: "Quale domanda 2 ci sar√† qui?"
    - title: "Domanda 3"
      question: "Quale domanda 3 ci sar√† qui?"

- name: "Candidature"
  description: "Proponiti per entrare nel nostro Staff"
  id: "candidature"
  emoji: "üìö"
  questions:
    - title: "Domanda 1"
      question: "Quale domanda 1 ci sar√† qui?"
    - title: "Domanda 2"
      question: "Quale domanda 2 ci sar√† qui?"
    - title: "Domanda 3"
      question: "Quale domanda 3 ci sar√† qui?"

- name: "Store"
  description: "Problematiche relative allo store"
  id: "store"
  emoji: "üí∞"
  questions:
    - title: "Domanda 1"
      question: "Quale domanda 1 ci sar√† qui?"
    - title: "Domanda 2"
      question: "Quale domanda 2 ci sar√† qui?"
    - title: "Domanda 3"
      question: "Quale domanda 3 ci sar√† qui?"